spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
#    data: classpath:data.sql
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/library
    username: library
    password: random123
    initialization-mode: always